version: '3.8'

services:
  nginx:
    container_name: dnd_nginx
    depends_on:
      - nest
      - next
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  next:
    container_name: dnd_next
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./next
    ports:
      - 3000:3000
    volumes:
      - ./next/node_modules:/app/node_modules
      - ./next:/app

  nest:
    container_name: dnd_nest
    build:
      context: ./nest
    env_file:
      - ./nest/.development.env
    volumes:
      - ./nest:/app
      - ./nest/node_modules:/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
    links:
      - mysql

  mysql:
    container_name: dnd_mysql
    image: mysql:8.0.28-oracle
    env_file:
      - ./nest/.development.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
