version: '3.8'

services:
  nginx:
    container_name: dnd_nginx
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
    container_name: dnd_client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client:/app

  server:
    container_name: dnd_server
    build:
      context: ./server
    env_file:
      - ./server/.development.env
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
    links:
      - mysql

  mysql:
    container_name: dnd_mysql
    image: mysql:8.0.28-oracle
    env_file:
      - ./server/.development.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql:rw

volumes:
  mysql:
    driver: local
